### ISSUE TITLE
006- f072503-No hay restricciones para enviar respuestas nulas

### ISSUE THREAD

**Issue by francodi65** [juanmadelboca/IngSoft-2016-2Cores4Threads#6]
f072503 - Si no selecciono ninguna respuesta, el boton enviar no tiene ninguna función, pero si selecciono una repuesta y luego la deselecciono, envía esta respuesta anteriormente seleccionada.
El botón enviar **debería estar disponible únicamente** cuando selecciono una respuesta.

**Comment by juanmadelboca** [comment]
Solucionado en 287ccfb
